---
name: Alien-Prototype
version: 1.6.0.1_0
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: installing and finding Prototype JS library
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.6.0
build_requires:
  Test::Exception: 0
provides:
  Alien::Prototype:
    file: lib/Alien/Prototype.pm
    version: 1.6.0.1_0
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
